export const competitionsInfo={
    competitions:[
        {
            code:"PL",
            bgColor:"#38003C",
        },
        {
            code:"FL1",
            bgColor:"#000",
        },
        {
            code:"ELC",
            bgColor:"#a69038",
        },
        {
            code:"BL1",
            bgColor:"#d10214",
        },
        {
            code:"SA",
            bgColor:"#e5002b",
        },
        {
            code:"EDE",
            bgColor:"#002f63",
        },
        {
            code:"PD",
            bgColor:"#004ad0",
        }
    ]
}
